version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "yandex"
      POSTGRES_USER: "puser"
      POSTGRES_PASSWORD: "ppaswd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      TZ: "Europe/Moscow"
    volumes:
      - ./tmp/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U puser -d yandex" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  agent:
    image: agent
    build:
      dockerfile: Dockerfile
      context: .
      args:
        COMPONENT: agent
    environment:
      ADDRESS: "server:8080"
      POLL_INTERVAL: "2s"
      REPORT_INTERVAL: "10s"
      KEY: "testkey"
      TZ: "Europe/Moscow"
    depends_on:
      server:
        condition: service_started
    restart: unless-stopped

  server:
    image: server
    build:
      dockerfile: Dockerfile
      context: .
      args:
        COMPONENT: server
    environment:
      ADDRESS: ":8080"
      STORE_INTERVAL: "300s"
      RESTORE: "true"
      KEY: "testkey"
      DATABASE_DSN: "postgres://puser:ppaswd@postgres:5432/yandex"
      TZ: "Europe/Moscow"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
