version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      TZ: "Europe/Moscow"
    volumes:
      - ./tmp/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  agent:
    image: agent
    environment:
      ADDRESS: "server:8080"
      POLL_INTERVAL: "2s"
      REPORT_INTERVAL: "10s"
      KEY: "testkey"
      TZ: "Europe/Moscow"
    restart: unless-stopped

  server:
    image: server
    environment:
      ADDRESS: ":8080"
      STORE_INTERVAL: "300s"
      RESTORE: "true"
      KEY: "testkey"
      DATABASE_DSN: "postgres://postgres:postgres@postgres:5432/postgres"
      TZ: "Europe/Moscow"
    ports:
      - "8080:8080"
    restart: unless-stopped
